### ISSUE TITLE
Set up development context

### ISSUE THREAD

**Issue by james-trimarco** [department-of-general-services/BOE_tabulator#13]
- Add `requirements.txt`
- Add to the ReadMe to show user how to replicate

**Comment by widal001** [comment]
@james-trimarco Here's my handle in case that helps you assign it to me

**Comment by robertnunn** [comment]
I doubt I'm using anything unique, but the non-standard library packages I've been using are:

- bs4
- requests
- PyPDF2

**Comment by james-trimarco** [comment]
@robertnunn Yes, those are the same packages that are in the main branch. So however we end up merging stuff together the current requirements.txt will be good.
