### ISSUE TITLE
Identify a list of analysis and process questions to be supported by this tool

### ISSUE THREAD

**Issue by james-trimarco** [department-of-general-services/BOE_tabulator#14]
Explore use cases and how this data can be used. 

What types of questions are most critical to be answered within the city?
What types of questions are most critical to users outside of the city?

Please store in this location:

`/discovery/operational_questions.md`

**Comment by james-trimarco** [comment]
@robertnunn committed a template for this document, but it'd be great to fill it out some

**Comment by brl1906** [comment]
> @robertnunn committed a template for this document, but it'd be great to fill it out some

I'm late to the party. working on this today plan to put something up soon. Thanks for the assist.

**Comment by james-trimarco** [comment]
Closing for now, since things have moved on a bit. When we come back to this topic, let's break it out into a new issue.
