### ISSUE TITLE
Unit Test Framework Setup

### ISSUE THREAD

**Issue by widal001** [department-of-general-services/BOE_tabulator#16]
Set up unit test framework and spec out initial set of tests for the existing code base. 

### In Scope
- Selection and installation of a testing library (i.e. pytest, unittest, etc.)
- Setup of a unit test sub-directory
- Creation of unit test methods/classes with doc strings describing what each method should be testing
- Update the README.md with instructions for how to run the tests upon installation and setup

### Out of Scope
- Writing actual tests. Tests should simply be substituted with `pass` or `assert True == True` and should be marked with `# TO DO:` comments for completion in a later issue.
- Adjusting any of the existing classes methods or functions to make them easier to test

**Comment by james-trimarco** [comment]
Perhaps this can get assigned to a team of several people, since it's of intermediate complexity. I'd be happy to be on that team. Interested in test-driven development!

**Comment by widal001** [comment]
@james-trimarco Sounds good I've been working on this issue in [this branch](https://github.com/widal001/BOE_tabulator/tree/issue-16) on my forked repo in case you want to set my repo as an upstream and then pull down my branch to work on it as well. Alternately I can create a branch for this issue on this repo and push my code to it if you want to drive collaboration through this repo
