### ISSUE TITLE
Implement pre-commit hooks

### ISSUE THREAD

**Issue by robertnunn** [department-of-general-services/BOE_tabulator#26]
testing auto-formatting to improve readability

**Comment by james-trimarco** [comment]
I'm interested in using the method described [in this article](https://ljvmiranda921.github.io/notebook/2018/06/21/precommits-using-black-and-flake8/). Definitely the formatter and maybe flake8. Folks OK with that?

**Comment by james-trimarco** [comment]
Here's [the process](https://ljvmiranda921.github.io/notebook/2018/06/21/precommits-using-black-and-flake8/) that I'd like to use.
